name: Move Trello Card to "Reviewing" on PR opened or updated

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master  # <-- tu rama por defecto

jobs:
  move_card_when_pull_request_opens:
    runs-on: ubuntu-latest
    name: Move Trello Card to "Reviewing" when PR refers to an issue
    steps:
      - name: Call trello-github-actions
        uses: Yleisradio/github-action-trello-integration@v1.1.0
        with:
          action: pull_request_event_move_card
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
          TRELLO_API_TOKEN: ${{ secrets.TRELLO_API_TOKEN }}
          TRELLO_BOARD_ID: 681f745a99f837a3cd55f56f
          TRELLO_SOURCE_LIST_ID: 681f8119a7693847221bc67b    # "Doing"
          TRELLO_TARGET_LIST_ID: 681f779a34f252719cb4b205    # "Reviewing"
