name: Sync Issue to Trello

on:
  issues:
    types: [opened]

jobs:
  create-card:
    runs-on: ubuntu-latest
    steps:
      - name: Create Trello Card
        env:
          TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
          TRELLO_API_TOKEN: ${{ secrets.TRELLO_API_TOKEN }}
          TRELLO_LIST_ID: ${{ secrets.TRELLO_LIST_ID }}
        run: |
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_BODY="${{ github.event.issue.body }}"
          ISSUE_URL="${{ github.event.issue.html_url }}"
          
          curl -X POST "https://api.trello.com/1/cards" \
            --data-urlencode "name=$ISSUE_TITLE" \
            --data-urlencode "desc=$ISSUE_BODY%0AIssue URL: $ISSUE_URL" \
            --data-urlencode "idList=$TRELLO_LIST_ID" \
            --data-urlencode "key=$TRELLO_API_KEY" \
            --data-urlencode "token=$TRELLO_API_TOKEN"
